# vim: ft=ansible
- name: Bootstrap proxmox
  hosts: proxmox
  become: true
  roles:
    - proxmox
  tags:
    - pve-bootstrap
    - proxmox

- name: Clusterize PVEs
  hosts: proxmox
  serial: 1
  become: true
  tasks:
    - name: Initializes cluster (only needed once, on the first node)
      command:
        argv:
         - pvecm
         - create
         - "{{ pve_cluster_name }}"
        creates: /etc/pve/corosync.conf
      when: "'pve_first_node' in group_names"

    - name: Join exisitng cluster
      command:
        argv:
          - pvecm
          - add
          - "{{ hostvars[groups['pve_first_node'][0]].pve_public_ip }}"
          - "-use_ssh"
        creates: /etc/pve/corosync.conf
      when: "'pve_first_node' not in group_names"
  tags:
    - pve-cluster
    - proxmox

- name: Configure network (wireguard & dnsmasq)
  hosts: proxmox
  roles:
    - wireguard
    - dnsmasq
  tags:
    - pve-network
    - proxmox

- name: Configure service-discovery (consul)
  hosts: proxmox
  serial: 1
  roles:
    - service_discovery
  tags:
    - service-discovery
    - ingress

- name: Configure incoming traffic (fabio)
  hosts: proxmox
  roles:
    - fabiolb
  tags:
    - ingress
    - fabio

